services:
  seerrfixarr:
    container_name: SeerrFixarr-dev
    environment:
      TZ: ${TZ}
      CULTURE: ${CULTURE}
      PORT: 80
      OVERSEERR__APIURL: ${OVERSEERR_API_URL}
      OVERSEERR__APIKEY: ${OVERSEERR_API_KEY}
      RADARR__APIURL: ${RADARR_API_URL}
      RADARR__APIKEY: ${RADARR_API_KEY}
      SONARR__APIURL: ${SONARR_API_URL}
      SONARR__APIKEY: ${SONARR_API_KEY}
      JWTSIGNINGKEY: "super-secret-key-used-for-signing"
      USERREDIRECTKEYPOOL: ${KEYPOOL}
    ports:
      - 8080:80
    build:
      context: .
      dockerfile: SeerrFixarr.App/Dockerfile
    volumes:
      - ${APPDATA}\SeerrFixarr\keys:/keys
    image: seerrfixarr.app